### ISSUE TITLE
"Open New External Terminal" command seems broken in VS Code 1.57.0

### ISSUE THREAD

**Issue by te-online** [fabiospampinato/vscode-open-in-terminal#7]
I get this error when running the command. Some API change in VS Code maybe?

```
[2021-06-14 15:40:20.791] [renderer5] [error] Cannot read property 'external' of undefined: TypeError: Cannot read property 'external' of undefined
    at It.spawnTerminal (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:31:151)
    at It.openTerminal (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:30:79128)
    at Object.call (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:21:8293)
    at h.onPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:7775)
    at h.onRawMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:7134)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:20:6387
    at k.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:46850
    at k.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1835)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:47016
    at k.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:16:1835)
    at IpcMainImpl.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:14:48719)
    at IpcMainImpl.emit (events.js:327:22)
    at Object.<anonymous> (electron/js2c/browser_init.js:165:9692)
    at Object.emit (events.js:315:20)
```

**Comment by te-online** [comment]
Nevermind, it works again 👍
